---
  version: '2'
  services:

    kibana:
      image: docker.elastic.co/kibana/kibana-oss:6.0.0
      container_name: docker-kibana
      links:
        - elasticsearch
      environment:
        SERVER_NAME: kibana.example.org
        ELASTICSEARCH_URL: http://172.18.0.2:9200
        TZ: America/Toronto
      ports:
        - 5601:5601
    elasticsearch:
      image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.0.0
      container_name: docker-elasticsearch
      environment:
        - "discovery.type=single-node"
        - "TZ=America/Toronto"
      ports:
        - 9200:9200
        - 9300:9300
    fluentd:
      build: ./fluentd
      container_name: docker-fluentd
      environment:
        - "TZ=America/Toronto"
      volumes:
        - ./fluentd/conf:/fluentd/etc
      links:
        - elasticsearch
      ports:
        - 24224:24224
        - 24224:24224/udp
        - 5140:5140
